### ISSUE TITLE
Incorrect dependency version of keycloak-orgs (v0.37) utilizes jakarta instead of javax

### ISSUE THREAD

**Issue by diazoxide** [p2-inc/phasetwo-containers#22]
In version `phasetwo-keycloak:21.1.2` image, an error occurs when accessing the admin organizations page.

<img width="1258" alt="image" src="https://github.com/p2-inc/phasetwo-containers/assets/25997814/c8008b2b-d7a9-4248-bb21-0af3c0793e00">

Error logs

```
2023-08-08T06:47:03.887716335Z 2023-08-08 06:47:03,886 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.NoClassDefFoundError: jakarta/ws/rs/NotAuthorizedException
2023-08-08T06:47:03.887759085Z 	at io.phasetwo.service.resource.OrganizationResourceProvider.getRealmResource(OrganizationResourceProvider.java:16)
2023-08-08T06:47:03.887762752Z 	at io.phasetwo.service.resource.BaseRealmResourceProvider.getResource(BaseRealmResourceProvider.java:30)
```

Upon a detailed examination of the error, I discovered that in libs/pom.xml, the version of keycloak-orgs is set to 0.37.
```
    <keycloak-orgs.version>0.37</keycloak-orgs.version>
```

And i noticed that `keycloak-orgs:0.37` already using `jakarta` instead of `javax`.

Improved Text:

In the original Keycloak 21.1.2 image, as well as the Bitnami version, the `jakarta` dependencies are absent. This is the reason for the observed error.

**Comment by xgp** [comment]
Looks like orgs was one version ahead in the pom. Thanks for the report. New image out soon.

**Comment by xgp** [comment]
@diazoxide new image is up that downgrades the orgs lib back to the last one with kc 21 compatibility. Please try `21.1.2.1691497549` when you get a chance and see if it solves your problem.
