### ISSUE TITLE
Container plugin does not work for keycloak version 21.1.2

### ISSUE THREAD

**Issue by henrywucoupa** [p2-inc/phasetwo-containers#26]
Hi Support,

I am working for software engineering team at Coupa Software. We are using Keycloak version 21.1.2 with phasetwo container source code https://github.com/p2-inc/phasetwo-containers **_v21.1.2.1688664025_**. We kept getting following error. Please see attached error1.txt and error2.txt files and let us know your recommendations. 

2023-09-20 22:18:53,321 DEBUG [io.quarkus.deployment.QuarkusAugmentor] (main) Beginning Quarkus augmentation
2023-09-20 22:18:53,881 DEBUG [io.quarkus.runtime.util.ContainerRuntimeUtil] (main) Failure to read info output from docker: java.io.IOException: Cannot run program "docker": error=2, No such file or directory
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
    at io.quarkus.runtime.util.ContainerRuntimeUtil.getRootlessStateFor(ContainerRuntimeUtil.java:71)
    at io.quarkus.runtime.util.ContainerRuntimeUtil$ContainerRuntime.<init>(ContainerRuntimeUtil.java:111)
    at io.quarkus.runtime.util.ContainerRuntimeUtil$ContainerRuntime.<clinit>(ContainerRuntimeUtil.java:105)

`2023-09-20 22:18:53,301 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[/ runtime=true resources=18] to QuarkusClassLoader Deployment Class Loader: PROD
2023-09-20 22:18:53,302 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[/ runtime=true resources=497] to QuarkusClassLoader Deployment Class Loader: PROD
2023-09-20 22:18:53,321 DEBUG [io.quarkus.deployment.QuarkusAugmentor] (main) Beginning Quarkus augmentation
2023-09-20 22:18:53,881 DEBUG [io.quarkus.runtime.util.ContainerRuntimeUtil] (main) Failure to read info output from docker: java.io.IOException: Cannot run program "docker": error=2, No such file or directory
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
    at io.quarkus.runtime.util.ContainerRuntimeUtil.getRootlessStateFor(ContainerRuntimeUtil.java:71)
    at io.quarkus.runtime.util.ContainerRuntimeUtil$ContainerRuntime.<init>(ContainerRuntimeUtil.java:111)
    at io.quarkus.runtime.util.ContainerRuntimeUtil$ContainerRuntime.<clinit>(ContainerRuntimeUtil.java:105)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at java.base/java.lang.Class.getEnumConstantsShared(Class.java:3837)
    at java.base/java.lang.Class.getEnumConstants(Class.java:3812)
    at io.quarkus.runtime.configuration.HyphenateEnumConverter.<init>(HyphenateEnumConverter.java:27)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
    at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.getConverter(BuildTimeConfigurationReader.java:822)
    at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.getConverter(BuildTimeConfigurationReader.java:865)
    at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.readConfigValue(BuildTimeConfigurationReader.java:776)
    at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.readConfigGroup(BuildTimeConfigurationReader.java:722)
    at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.run(BuildTimeConfigurationReader.java:361)
    at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.lambda$readConfiguration$0(BuildTimeConfigurationReader.java:322)
    at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:29)
    at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.readConfiguration(BuildTimeConfigurationReader.java:322)
    at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:195)
    at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
    at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
    at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:175)
    at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:84)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
    at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:75)
    at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
    at picocli.CommandLine.access$1300(CommandLine.java:145)
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
    at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
    at picocli.CommandLine.execute(CommandLine.java:2078)
    at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentation(Picocli.java:184)
    at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:121)
    at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:89)
    at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
    at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
    at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
    ... 55 more

2023-09-20 22:18:53,892 DEBUG [io.quarkus.runtime.util.ContainerRuntimeUtil] (main) Failure to read info output from podman: java.io.IOException: Cannot run program "podman": error=2, No such file or directory
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
    at io.quarkus.runtime.util.ContainerRuntimeUtil.getRootlessStateFor(ContainerRuntimeUtil.java:71)
    at io.quarkus.runtime.util.ContainerRuntimeUtil$ContainerRuntime.<init>(ContainerRuntimeUtil.java:111)
    at io.quarkus.runtime.util.ContainerRuntimeUtil$ContainerRuntime.<clinit>(ContainerRuntimeUtil.java:106)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at java.base/java.lang.Class.getEnumConstantsShared(Class.java:3837)
    at java.base/java.lang.Class.getEnumConstants(Class.java:3812)
    at io.quarkus.runtime.configuration.HyphenateEnumConverter.<init>(HyphenateEnumConverter.java:27)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
    at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.getConverter(BuildTimeConfigurationReader.java:822)
    at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.getConverter(BuildTimeConfigurationReader.java:865)
    at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.readConfigValue(BuildTimeConfigurationReader.java:776)
    at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.readConfigGroup(BuildTimeConfigurationReader.java:722)
    at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.run(BuildTimeConfigurationReader.java:361)
    at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.lambda$readConfiguration$0(BuildTimeConfigurationReader.java:322)
    at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:29)
    at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.readConfiguration(BuildTimeConfigurationReader.java:322)
    at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:195)
    at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
    at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
    at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:175)
    at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:84)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
    at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:75)
    at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
    at picocli.CommandLine.access$1300(CommandLine.java:145)
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
    at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
    at picocli.CommandLine.execute(CommandLine.java:2078)
    at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentation(Picocli.java:184)
    at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:121)
    at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:89)
    at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
    at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
    at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
    ... 55 more

2023-09-20 22:18:54,404 DEBUG [io.quarkus.micrometer.runtime.MicrometerRecorder] (main) getClass: TCCL: QuarkusClassLoader:Deployment Class Loader: PROD@5feff876 ## io.grpc.ClientInterceptor : false
2023-09-20 22:18:54,405 DEBUG [io.quarkus.micrometer.runtime.MicrometerRecorder] (main) getClass: TCCL: QuarkusClassLoader:Deployment Class Loader: PROD@5feff876 ## io.grpc.ServerInterceptor : false
2023-09-20 22:18:54,407 DEBUG [io.quarkus.micrometer.runtime.MicrometerRecorder] (main) getClass: TCCL: QuarkusClassLoader:Deployment Class Loader: PROD@5feff876 ## org.apache.kafka.clients.consumer.Consumer : false
2023-09-20 22:18:54,408 DEBUG [io.quarkus.micrometer.runtime.MicrometerRecorder] (main) getClass: TCCL: QuarkusClassLoader:Deployment Class Loader: PROD@5feff876 ## org.apache.kafka.streams.KafkaStreams : false
2023-09-20 22:18:54,409 DEBUG [io.quarkus.micrometer.runtime.MicrometerRecorder] (main) getClass: TCCL: QuarkusClassLoader:Deployment Class Loader: PROD@5feff876 ## io.vertx.core.metrics.MetricsOptions : true
2023-09-20 22:18:54,412 DEBUG [io.quarkus.micrometer.runtime.MicrometerRecorder] (main) getClass: TCCL: QuarkusClassLoader:Deployment Class Loader: PROD@5feff876 ## org.eclipse.microprofile.metrics.annotation.Metric : false
2023-09-20 22:18:54,418 DEBUG [io.quarkus.micrometer.runtime.MicrometerRecorder] (main) getClass: TCCL: QuarkusClassLoader:Deployment Class Loader: PROD@5feff876 ## io.micrometer.prometheus.PrometheusMeterRegistry : true
2023-09-20 22:18:54,803 DEBUG [io.quarkus.deployment] (main) Build steps with ambiguous name detected: io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor#setupDevConsoleRoutes, using discriminator suffix for step id: io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor#setupDevConsoleRoutes_8bb86a3e770caadb970f4facb490e30df7a2a187
2023-09-20 22:18:54,804 DEBUG [io.quarkus.deployment] (main) Build steps with ambiguous name detected: io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor#setupDevConsoleRoutes, using discriminator suffix for step id: io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor#setupDevConsoleRoutes_0a9629c46f632dba90d4b3c7602ae4ea9d736452
2023-09-20 22:18:54,823 DEBUG [io.quarkus.deployment] (main) Build steps with ambiguous name detected: io.quarkus.vertx.core.deployment.VertxCoreProcessor#build, using discriminator suffix for step id: io.quarkus.vertx.core.deployment.VertxCoreProcessor#build_9fb3ce360263cc99d07c9172ec2feeaa85afcc1a
2023-09-20 22:18:54,823 DEBUG [io.quarkus.deployment] (main) Build steps with ambiguous name detected: io.quarkus.vertx.core.deployment.VertxCoreProcessor#build, using discriminator suffix for step id: io.quarkus.vertx.core.deployment.VertxCoreProcessor#build_9d6b7122fb368970c50c3a870d1f672392cd8afb
2023-09-20 22:18:54,892 DEBUG [io.quarkus.deployment] (main) Build steps with ambiguous name detected: io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build, using discriminator suffix for step id: io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build_7a4403d699506d83ac39616f3c11e5e1b448d863
2023-09-20 22:18:54,892 DEBUG [io.quarkus.deployment] (main) Build steps with ambiguous name detected: io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build, using discriminator suffix for step id: io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build_daeea4f2c9416db083cc1423ec1bf5c757ad2a16
2023-09-20 22:18:54,989 DEBUG [org.jboss.threads] (main) JBoss Threads version 3.4.3.Final
2023-09-20 22:18:55,071 DEBUG [io.quarkus.hibernate.orm.runtime.service.FlatClassLoaderService] (build-11) locateResources (plural form) was invoked for resource 'META-INF/persistence.xml'. Is there a real need for this plural form?
2023-09-20 22:18:55,076 DEBUG [io.quarkus.netty.deployment.NettyProcessor] (build-27) Not registering Netty native kqueue classes as they were not found
2023-09-20 22:18:55,127 DEBUG [io.quarkus.deployment.steps.ApplicationIndexBuildStep] (build-20) Indexing /org/keycloak/quarkus/_private/IDELauncher.class
2023-09-20 22:18:55,170 DEBUG [io.quarkus.micrometer.deployment.export.PrometheusRegistryProcessor] (build-18) PROMETHEUS CONFIG: PrometheusConfigGroup{path='metrics,enabled=Optional.empty,defaultRegistry=true}
2023-09-20 22:18:55,174 DEBUG [io.quarkus.deployment.steps.NativeImageConfigBuildStep] (build-19) Native SSL support enabled due to extensions [agroal] requiring it
2023-09-20 22:18:55,209 DEBUG [org.keycloak.provider.ProviderManager] (build-7) Provider loaders [org.keycloak.provider.DefaultProviderLoaderFactory@3a5b9220, org.keycloak.provider.FileSystemProviderLoaderFactory@42be96e1]
2023-09-20 22:18:55,301 DEBUG [io.netty.util.internal.PlatformDependent0] (build-21) -Dio.netty.noUnsafe: false
2023-09-20 22:18:55,301 DEBUG [io.netty.util.internal.PlatformDependent0] (build-21) Java version: 17
2023-09-20 22:18:55,305 DEBUG [io.netty.util.internal.PlatformDependent0] (build-21) java.nio.Buffer.address: available
2023-09-20 22:18:55,307 DEBUG [io.netty.util.internal.PlatformDependent0] (build-21) java.nio.Bits.unaligned: available, true
2023-09-20 22:18:55,313 DEBUG [io.netty.util.internal.PlatformDependent0] (build-21) java.nio.DirectByteBuffer.<init>(long, int): unavailable
2023-09-20 22:18:55,313 DEBUG [io.netty.util.internal.PlatformDependent] (build-21) sun.misc.Unsafe: available
2023-09-20 22:18:55,314 DEBUG [io.netty.util.internal.PlatformDependent] (build-21) maxDirectMemory: 4294967296 bytes (maybe)
2023-09-20 22:18:55,314 DEBUG [io.netty.util.internal.PlatformDependent] (build-21) -Dio.netty.tmpdir: /tmp (java.io.tmpdir)

`

Thanks so much.
Henry Wu

**Comment by xgp** [comment]
@henrywucoupa Thanks for the report. Can you please tell me how you are starting the container? There are a few flags that must be set for our image. E.g. try this out and see if you have the same problems:
```
docker run --name phasetwo_test --rm -p 8080:8080 \
    -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_HTTP_RELATIVE_PATH=/auth \
    quay.io/phasetwo/phasetwo-keycloak:$VERSION \
    start-dev --spi-email-template-provider=freemarker-plus-mustache --spi-email-template-freemarker-plus-mustache-enabled=true --spi-theme-cache-themes=false
```

Also, please upgrade to the most recent version, as there have been many changes.
