### ISSUE TITLE
Error with certificate when I add a custom spi

### ISSUE THREAD

**Issue by mrp4sten** [p2-inc/phasetwo-containers#47]
Actually I have a Dockerfile like this:

```Dockerfile
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY modules/kc-authenticator/pom.xml .
COPY modules/kc-authenticator/src src

RUN mvn dependency:go-offline -B
RUN mvn package

FROM quay.io/phasetwo/phasetwo-keycloak:24.0.4 AS kc-build
WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/phasetwo/phasetwo-keycloak:24.0.4 AS keycloak
WORKDIR /opt/keycloak/
COPY --from=kc-build /opt/keycloak/ ./
COPY --from=build /app/target/niche-otp-authenticator.jar providers/

EXPOSE 8080

CMD ["/opt/keycloak/bin/kc.sh"]
``` 

I run the container like this: 

```shell
docker run -it --name phasetwo_test --rm -p 8080:8080 \
    -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_HTTP_RELATIVE_PATH=/auth \
    MY_DOCKER_IMAGE \
    start-dev --verbose --spi-email-template-provider=freemarker-plus-mustache --spi-email-template-freemarker-plus-mustache-enabled=true --spi-theme-cache-themes=false
``` 

And I have an error like this

```shell
2024-05-20 22:43:33,437 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2024-05-20 22:43:33,437 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: org.keycloak.component.ComponentValidationException: Failed to generate certificate
	at org.keycloak.keys.AbstractGeneratedRsaKeyProviderFactory.generateCertificate(AbstractGeneratedRsaKeyProviderFactory.java:125)
	at org.keycloak.keys.AbstractGeneratedRsaKeyProviderFactory.generateKeys(AbstractGeneratedRsaKeyProviderFactory.java:113)
	at org.keycloak.keys.AbstractGeneratedRsaKeyProviderFactory.validateConfiguration(AbstractGeneratedRsaKeyProviderFactory.java:86)
	at org.keycloak.models.jpa.RealmAdapter.importComponentModel(RealmAdapter.java:2059)
	at org.keycloak.models.jpa.RealmAdapter.addComponentModel(RealmAdapter.java:2039)
	at org.keycloak.models.utils.DefaultKeyProviders.createRsaKeyProvider(DefaultKeyProviders.java:61)
	at org.keycloak.models.utils.DefaultKeyProviders.createProviders(DefaultKeyProviders.java:38)
	at org.keycloak.services.managers.ApplianceBootstrap.createMasterRealm(ApplianceBootstrap.java:93)
	at org.keycloak.services.resources.KeycloakApplication$2.run(KeycloakApplication.java:196)
	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:257)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:379)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:256)
	at org.keycloak.services.resources.KeycloakApplication.bootstrap(KeycloakApplication.java:167)
	at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:143)
	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:257)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:379)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:256)
	at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:135)
	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.onStartupEvent(QuarkusKeycloakApplication.java:54)
	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication_Observer_onStartupEvent_GNZ8m5QenZ9h9VNelo7awjUZFDE.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:108)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:33)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:125)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: java.lang.NoSuchFieldError: id_alg_zlibCompress
	at org.bouncycastle.asn1.cms.CMSObjectIdentifiers.<clinit>(Unknown Source)
	at org.bouncycastle.operator.DefaultSignatureNameFinder.<clinit>(Unknown Source)
	at org.bouncycastle.operator.jcajce.OperatorHelper.<clinit>(Unknown Source)
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.<init>(Unknown Source)
	at org.keycloak.crypto.def.BCCertificateUtilsProvider.createSigner(BCCertificateUtilsProvider.java:183)
	at org.keycloak.crypto.def.BCCertificateUtilsProvider.generateV1SelfSignedCertificate(BCCertificateUtilsProvider.java:164)
	at org.keycloak.crypto.def.BCCertificateUtilsProvider.generateV1SelfSignedCertificate(BCCertificateUtilsProvider.java:150)
	at org.keycloak.common.util.CertificateUtils.generateV1SelfSignedCertificate(CertificateUtils.java:63)
	at org.keycloak.keys.AbstractGeneratedRsaKeyProviderFactory.generateCertificate(AbstractGeneratedRsaKeyProviderFactory.java:118)
	... 48 more
```

This error not occur when I comment the line on my dockerfile: 

```shell
COPY --from=build /app/target/niche-otp-authenticator.jar providers/
```

**Comment by xgp** [comment]
> This error not occur when I comment the line on my dockerfile:
> 
> COPY --from=build /app/target/niche-otp-authenticator.jar providers/

It sounds like this is an issue with your extension. Without knowing what's in it, I'd have no idea how to help you. I'd suggest you try this with the standard Keycloak docker image, and then ask for help from their [Github](https://github.com/keycloak/keycloak) or [Discourse](https://keycloak.discourse.group/), as this question doesn't have anything to do with our image.
